//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POE2Tools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int trkUpdateRate {
            get {
                return ((int)(this["trkUpdateRate"]));
            }
            set {
                this["trkUpdateRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkDebugMode {
            get {
                return ((bool)(this["chkDebugMode"]));
            }
            set {
                this["chkDebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string txtFlaskCooldown1 {
            get {
                return ((string)(this["txtFlaskCooldown1"]));
            }
            set {
                this["txtFlaskCooldown1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskHighLife1 {
            get {
                return ((bool)(this["chkFlaskHighLife1"]));
            }
            set {
                this["chkFlaskHighLife1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskLowLife1 {
            get {
                return ((bool)(this["chkFlaskLowLife1"]));
            }
            set {
                this["chkFlaskLowLife1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskHighShield1 {
            get {
                return ((bool)(this["chkFlaskHighShield1"]));
            }
            set {
                this["chkFlaskHighShield1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskLowShield1 {
            get {
                return ((bool)(this["chkFlaskLowShield1"]));
            }
            set {
                this["chkFlaskLowShield1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskHighMana1 {
            get {
                return ((bool)(this["chkFlaskHighMana1"]));
            }
            set {
                this["chkFlaskHighMana1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskLowMana1 {
            get {
                return ((bool)(this["chkFlaskLowMana1"]));
            }
            set {
                this["chkFlaskLowMana1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskCooldown1 {
            get {
                return ((bool)(this["chkFlaskCooldown1"]));
            }
            set {
                this["chkFlaskCooldown1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtFlaskCooldown2 {
            get {
                return ((string)(this["txtFlaskCooldown2"]));
            }
            set {
                this["txtFlaskCooldown2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskHighLife2 {
            get {
                return ((bool)(this["chkFlaskHighLife2"]));
            }
            set {
                this["chkFlaskHighLife2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskLowLife2 {
            get {
                return ((bool)(this["chkFlaskLowLife2"]));
            }
            set {
                this["chkFlaskLowLife2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskHighShield2 {
            get {
                return ((bool)(this["chkFlaskHighShield2"]));
            }
            set {
                this["chkFlaskHighShield2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskLowShield2 {
            get {
                return ((bool)(this["chkFlaskLowShield2"]));
            }
            set {
                this["chkFlaskLowShield2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskHighMana2 {
            get {
                return ((bool)(this["chkFlaskHighMana2"]));
            }
            set {
                this["chkFlaskHighMana2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskLowMana2 {
            get {
                return ((bool)(this["chkFlaskLowMana2"]));
            }
            set {
                this["chkFlaskLowMana2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskCooldown2 {
            get {
                return ((bool)(this["chkFlaskCooldown2"]));
            }
            set {
                this["chkFlaskCooldown2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtSkillCooldown1 {
            get {
                return ((string)(this["txtSkillCooldown1"]));
            }
            set {
                this["txtSkillCooldown1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighLife1 {
            get {
                return ((bool)(this["chkSkillHighLife1"]));
            }
            set {
                this["chkSkillHighLife1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowLife1 {
            get {
                return ((bool)(this["chkSkillLowLife1"]));
            }
            set {
                this["chkSkillLowLife1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighShield1 {
            get {
                return ((bool)(this["chkSkillHighShield1"]));
            }
            set {
                this["chkSkillHighShield1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowShield1 {
            get {
                return ((bool)(this["chkSkillLowShield1"]));
            }
            set {
                this["chkSkillLowShield1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighMana1 {
            get {
                return ((bool)(this["chkSkillHighMana1"]));
            }
            set {
                this["chkSkillHighMana1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowMana1 {
            get {
                return ((bool)(this["chkSkillLowMana1"]));
            }
            set {
                this["chkSkillLowMana1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillCooldown1 {
            get {
                return ((bool)(this["chkSkillCooldown1"]));
            }
            set {
                this["chkSkillCooldown1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtSkillCooldown2 {
            get {
                return ((string)(this["txtSkillCooldown2"]));
            }
            set {
                this["txtSkillCooldown2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighLife2 {
            get {
                return ((bool)(this["chkSkillHighLife2"]));
            }
            set {
                this["chkSkillHighLife2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowLife2 {
            get {
                return ((bool)(this["chkSkillLowLife2"]));
            }
            set {
                this["chkSkillLowLife2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighShield2 {
            get {
                return ((bool)(this["chkSkillHighShield2"]));
            }
            set {
                this["chkSkillHighShield2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowShield2 {
            get {
                return ((bool)(this["chkSkillLowShield2"]));
            }
            set {
                this["chkSkillLowShield2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighMana2 {
            get {
                return ((bool)(this["chkSkillHighMana2"]));
            }
            set {
                this["chkSkillHighMana2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowMana2 {
            get {
                return ((bool)(this["chkSkillLowMana2"]));
            }
            set {
                this["chkSkillLowMana2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillCooldown2 {
            get {
                return ((bool)(this["chkSkillCooldown2"]));
            }
            set {
                this["chkSkillCooldown2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtSkillCooldown3 {
            get {
                return ((string)(this["txtSkillCooldown3"]));
            }
            set {
                this["txtSkillCooldown3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighLife3 {
            get {
                return ((bool)(this["chkSkillHighLife3"]));
            }
            set {
                this["chkSkillHighLife3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowLife3 {
            get {
                return ((bool)(this["chkSkillLowLife3"]));
            }
            set {
                this["chkSkillLowLife3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighShield3 {
            get {
                return ((bool)(this["chkSkillHighShield3"]));
            }
            set {
                this["chkSkillHighShield3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowShield3 {
            get {
                return ((bool)(this["chkSkillLowShield3"]));
            }
            set {
                this["chkSkillLowShield3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighMana3 {
            get {
                return ((bool)(this["chkSkillHighMana3"]));
            }
            set {
                this["chkSkillHighMana3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowMana3 {
            get {
                return ((bool)(this["chkSkillLowMana3"]));
            }
            set {
                this["chkSkillLowMana3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillCooldown3 {
            get {
                return ((bool)(this["chkSkillCooldown3"]));
            }
            set {
                this["chkSkillCooldown3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtSkillCooldown4 {
            get {
                return ((string)(this["txtSkillCooldown4"]));
            }
            set {
                this["txtSkillCooldown4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighLife4 {
            get {
                return ((bool)(this["chkSkillHighLife4"]));
            }
            set {
                this["chkSkillHighLife4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowLife4 {
            get {
                return ((bool)(this["chkSkillLowLife4"]));
            }
            set {
                this["chkSkillLowLife4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighShield4 {
            get {
                return ((bool)(this["chkSkillHighShield4"]));
            }
            set {
                this["chkSkillHighShield4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowShield4 {
            get {
                return ((bool)(this["chkSkillLowShield4"]));
            }
            set {
                this["chkSkillLowShield4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighMana4 {
            get {
                return ((bool)(this["chkSkillHighMana4"]));
            }
            set {
                this["chkSkillHighMana4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowMana4 {
            get {
                return ((bool)(this["chkSkillLowMana4"]));
            }
            set {
                this["chkSkillLowMana4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillCooldown4 {
            get {
                return ((bool)(this["chkSkillCooldown4"]));
            }
            set {
                this["chkSkillCooldown4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtSkillCooldown5 {
            get {
                return ((string)(this["txtSkillCooldown5"]));
            }
            set {
                this["txtSkillCooldown5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighLife5 {
            get {
                return ((bool)(this["chkSkillHighLife5"]));
            }
            set {
                this["chkSkillHighLife5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowLife5 {
            get {
                return ((bool)(this["chkSkillLowLife5"]));
            }
            set {
                this["chkSkillLowLife5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighShield5 {
            get {
                return ((bool)(this["chkSkillHighShield5"]));
            }
            set {
                this["chkSkillHighShield5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowShield5 {
            get {
                return ((bool)(this["chkSkillLowShield5"]));
            }
            set {
                this["chkSkillLowShield5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighMana5 {
            get {
                return ((bool)(this["chkSkillHighMana5"]));
            }
            set {
                this["chkSkillHighMana5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowMana5 {
            get {
                return ((bool)(this["chkSkillLowMana5"]));
            }
            set {
                this["chkSkillLowMana5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillCooldown5 {
            get {
                return ((bool)(this["chkSkillCooldown5"]));
            }
            set {
                this["chkSkillCooldown5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkDrawText {
            get {
                return ((bool)(this["chkDrawText"]));
            }
            set {
                this["chkDrawText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int trkColorTolerance {
            get {
                return ((int)(this["trkColorTolerance"]));
            }
            set {
                this["trkColorTolerance"] = value;
            }
        }
    }
}
